function [allData, scenario, sensors] = NCCAR()
%NCCAR - Returns sensor detections
%    allData = NCCAR returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = NCCAR optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 10-Apr-2024 18:54:27

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
[sensors, numSensors] = createSensors(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    % Get the state of the ego vehicle
    actorState = state(egoVehicle);
    time  = scenario.SimulationTime;

    objectDetections = {};
    laneDetections   = [];
    ptClouds = {};
    insMeas = {};
    isValidTime = false(1, numSensors);
    isValidLaneTime = false(1, numSensors);
    isValidPointCloudTime = false(1, numSensors);
    isValidINSTime = false(1, numSensors);

    % Generate detections for each sensor
    for sensorIndex = 1:numSensors
        sensor = sensors{sensorIndex};
        % Generate the ego vehicle lane boundaries
        if isa(sensor, 'visionDetectionGenerator')
            maxLaneDetectionRange = min(500,sensor.MaxRange);
            lanes = laneBoundaries(egoVehicle, 'XDistance', linspace(-maxLaneDetectionRange, maxLaneDetectionRange, 101));
        end
        type = getDetectorOutput(sensor);
        if strcmp(type, 'Objects only')
            if isa(sensor,'ultrasonicDetectionGenerator')
                [objectDets, isValidTime(sensorIndex)] = sensor(poses, time);
                numObjects = length(objectDets);
            else
                [objectDets, numObjects, isValidTime(sensorIndex)] = sensor(poses, time);
            end
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes only')
            [laneDets, ~, isValidTime(sensorIndex)] = sensor(lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes and objects')
            [objectDets, numObjects, isValidTime(sensorIndex), laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes with occlusion')
            [laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'PointCloud')
            if sensor.HasRoadsInputPort
                rdmesh = roadMesh(egoVehicle,min(500,sensor.MaxRange));
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, rdmesh, time);
            else
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, time);
            end
            ptClouds = [ptClouds; ptCloud]; %#ok<AGROW>
        elseif strcmp(type, 'INSMeasurement')
            insMeasCurrent = sensor(actorState, time);
            insMeas = [insMeas; insMeasCurrent]; %#ok<AGROW>
            isValidINSTime(sensorIndex) = true;
        end
    end

    % Aggregate all detections into a structure for later use
    if any(isValidTime) || any(isValidLaneTime) || any(isValidPointCloudTime) || any(isValidINSTime)
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release all the sensor objects so they can be used again.
for sensorIndex = 1:numSensors
    release(sensors{sensorIndex});
end

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function [sensors, numSensors] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensors{1} = insSensor('TimeInput', true);
sensors{2} = visionDetectionGenerator('SensorIndex', 2, ...
    'SensorLocation', [1.5 0], ...
    'HasNoise', false, ...
    'DetectionProbability', 1, ...
    'FalsePositivesPerImage', 0, ...
    'DetectorOutput', 'Lanes only', ...
    'Intrinsics', cameraIntrinsics([554.256 311.769145362398],[960 540],[1080 1920]), ...
    'ActorProfiles', profiles);
numSensors = 2;

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('GeoReference', [36.479835 -77.57791 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [18 -400 0;
    24.0649580066019 -517.193260613925 0;
    47.9750875785322 -536.235754667303 0;
    76.6624478766495 -523.86324919821 0;
    92.9207165458355 -401.033127036538 0;
    170.3867343289 -327.239977647937 0;
    175.638329011851 -310.583707423304 0;
    220.589417862495 -94.9286389485818 0;
    369.284691020735 35.5160409637706 0;
    376.928401491428 50.2749423777918 0;
    383.621758729161 83.5987651522238 0;
    323.857116789485 188.318052659596 0;
    249.272937073171 204.507402924895 0;
    203.848829308523 146.426557679798 0;
    230.150558692309 53.6019700547394 0;
    220.105120680016 -1.61571858138137 0;
    173.254881446187 -44.9376574339232 0;
    123.527790307155 -52.5609411441475 0;
    72.6630287615676 -20.1134079563903 0;
    77.0904329809449 17.0164034834116 0;
    87.5307589250409 45.4684566610883 0;
    73.1034401434289 80.1461122044347 0;
    72.0105163889276 107.311078655012 0;
    103.922000574666 145.006530880687 0;
    109.666332907755 164.991806883824 0;
    94.8451425487286 229.264591330367 0;
    154.132464853073 315.419707487138 0;
    195.24584480359 312.090617826022 0;
    244.971069253516 276.858486287906 0;
    294.696108072602 288.288674570601 0;
    310.951091560049 318.749605568912 0;
    301.380240074167 351.129928799823 0;
    287.517385640031 363.025521607973 0;
    148.388951278336 439.670587819864 0;
    108.235046546122 446.328932608309 0;
    27.9085385256614 406.825415466225 0;
    5.44255812286789 367.310152431137 0;
    1.61556779338585 337.326683360315 0;
    15.7973364726795 -301.038813069664 0;
    18 -400 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid', 'Color', [0.98 0.86 0.36])];
laneSpecification = lanespec([1 1], 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'NCCAR');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 0.119999999999996 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [0 0.119999999999996 0;
    48.1 -536.4 0;
    383.6 83.7 0;
    249.3 204.5 0;
    230.6 54 0;
    123.5 -52.6 0;
    72.7 -20 0;
    154.3 315.9 0;
    295.8 287.7 0;
    109.6 447.6 0;
    1.7 338.4 0;
    1 0 0];
speed = [10;10;10;10;10;10;10;10;10;10;10;10];
yaw =  [-90;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN];
smoothTrajectory(egoVehicle, waypoints, speed, 'Yaw', yaw);

function output = getDetectorOutput(sensor)

if isa(sensor, 'visionDetectionGenerator')
    output = sensor.DetectorOutput;
elseif isa(sensor, 'lidarPointCloudGenerator')
    output = 'PointCloud';
elseif isa(sensor, 'insSensor')
    output = 'INSMeasurement';
else
    output = 'Objects only';
end

