function cost = mpcCostFunction(x, u, Ts, L, waypoints, weights)

    cost_progress=progress_costFunc(x, waypoints, weights(3:4));
    cost_inputs=input_costFunc(u, weights(1:2));
    cost_obstacleAvoidance=0;
    cost_laneKeeping=0;
    cost_RL=0;
    cost_softConstraints=0;
    
    cost= cost_progress + ...
        cost_inputs + ...
        cost_laneKeeping + ...
        cost_obstacleAvoidance + ...
        cost_RL + ...
        cost_softConstraints;
end