function cost = mpcCostFunction(x, u, Ts, egoCar_params, waypoints, boundaries, tracks, weights)
    cost_progress=0;
    cost_inputs=input_costFun(u,weights.input);
    cost_laneKeeping=0;
    cost_obstacleAvoidance=0;
    cost_RL=0;
    cost_softConstraints=0;
    
    cost= cost_progress + ...
        cost_inputs + ...
        cost_laneKeeping + ...
        cost_obstacleAvoidance + ...
        cost_RL + ...
        cost_softConstraints;
end